---
apiVersion: v1
kind: Pod
metadata:
  name: build-service-pod
spec:
  containers:
    - name: kaniko
      image: gcr.io/kaniko-project/executor:debug
      command:
        - /busybox/cat
      tty: true
      volumeMounts:
        - name: kaniko-secret
          mountPath: /kaniko/.docker
        - name: kaniko-workspace
          mountPath: /kaniko/workspace
          readOnly: false
    - name: git
      image: alpine/git:2.36.2
      command: ["cat"]
      tty: true
      volumeMounts:
        - name: kaniko-workspace
          mountPath: /kaniko/workspace
          readOnly: false
    - name: helm-cli
      image: lachlanevenson/k8s-helm
      command: ["cat"]
      tty: true
      volumeMounts:
        - name: kaniko-workspace
          mountPath: /kaniko/workspace
          readOnly: false          
  volumes:
    - name: kaniko-secret
      secret:
        secretName: registry
        items:
          - key: .dockerconfigjson
            path: config.json
    - name: kaniko-workspace
      persistentVolumeClaim:
        claimName: jenkins-build